# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TMS(object):
    def setupUi(self, TMS):
        TMS.setObjectName("TMS")
        TMS.resize(872, 600)
        self.centralwidget = QtWidgets.QWidget(TMS)
        self.centralwidget.setObjectName("centralwidget")
        self.method1 = QtWidgets.QCheckBox(self.centralwidget)
        self.method1.setGeometry(QtCore.QRect(607, 19, 96, 19))
        self.method1.setStyleSheet("font: 9pt \"푸라닭 젠틀 고딕\";")
        self.method1.setObjectName("method1")
        self.buttonGroup = QtWidgets.QButtonGroup(TMS)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.method1)
        self.method2 = QtWidgets.QCheckBox(self.centralwidget)
        self.method2.setGeometry(QtCore.QRect(607, 49, 96, 19))
        self.method2.setStyleSheet("font: 9pt \"푸라닭 젠틀 고딕\";")
        self.method2.setObjectName("method2")
        self.buttonGroup.addButton(self.method2)
        self.method3 = QtWidgets.QCheckBox(self.centralwidget)
        self.method3.setGeometry(QtCore.QRect(607, 79, 96, 19))
        self.method3.setStyleSheet("font: 9pt \"푸라닭 젠틀 고딕\";")
        self.method3.setObjectName("method3")
        self.buttonGroup.addButton(self.method3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(310, 490, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.localBox = QtWidgets.QComboBox(self.centralwidget)
        self.localBox.setGeometry(QtCore.QRect(120, 90, 101, 31))
        self.localBox.setObjectName("localBox")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.localBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 161, 71))
        self.label.setStyleSheet("font: 36pt \"강원교육튼튼\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 51, 51))
        self.label_2.setStyleSheet("font: 12pt \"푸라닭 젠틀 고딕\";")
        self.label_2.setObjectName("label_2")
        self.cond1 = QtWidgets.QCheckBox(self.centralwidget)
        self.cond1.setGeometry(QtCore.QRect(40, 170, 96, 19))
        self.cond1.setObjectName("cond1")
        self.cond2 = QtWidgets.QCheckBox(self.centralwidget)
        self.cond2.setGeometry(QtCore.QRect(40, 200, 96, 19))
        self.cond2.setObjectName("cond2")
        self.cond3 = QtWidgets.QCheckBox(self.centralwidget)
        self.cond3.setGeometry(QtCore.QRect(40, 230, 96, 19))
        self.cond3.setObjectName("cond3")
        TMS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TMS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 26))
        self.menubar.setObjectName("menubar")
        TMS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TMS)
        self.statusbar.setObjectName("statusbar")
        TMS.setStatusBar(self.statusbar)

        self.retranslateUi(TMS)
        QtCore.QMetaObject.connectSlotsByName(TMS)

    def retranslateUi(self, TMS):
        _translate = QtCore.QCoreApplication.translate
        TMS.setWindowTitle(_translate("TMS", "MainWindow"))
        self.method1.setText(_translate("TMS", "순차 진행"))
        self.method2.setText(_translate("TMS", "동시 진행"))
        self.method3.setText(_translate("TMS", "GA"))
        self.localBox.setItemText(0, _translate("TMS", "파주"))
        self.localBox.setItemText(1, _translate("TMS", "구미"))
        self.localBox.setItemText(2, _translate("TMS", "광주"))
        self.localBox.setItemText(3, _translate("TMS", "여수"))
        self.localBox.setItemText(4, _translate("TMS", "창원"))
        self.localBox.setItemText(5, _translate("TMS", "익산"))
        self.localBox.setItemText(6, _translate("TMS", "미국"))
        self.localBox.setItemText(7, _translate("TMS", "울산"))
        self.label.setText(_translate("TMS", "TMS"))
        self.label_2.setText(_translate("TMS", "지역"))
        self.cond1.setText(_translate("TMS", "1"))
        self.cond2.setText(_translate("TMS", "2"))
        self.cond3.setText(_translate("TMS", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TMS = QtWidgets.QMainWindow()
    ui = Ui_TMS()
    ui.setupUi(TMS)
    TMS.show()
    sys.exit(app.exec_())
